import RequestProject.EFMW.Dynamics

/-!
# EFMW: force and cosmology sector (ME-051 … ME-058)

The corpus proposes a coherence-restoring "emergence force", a scalar fifth
force, a modified geodesic equation, and a rotating-universe extension of the
Friedmann equation.  This file states these precisely and proves what follows
from them: that the emergence force really is restoring towards the coherent
minima, that the modified geodesic equation reduces to the standard one when the
coupling vanishes, and that the rotation term strictly increases the expansion
rate exactly when the residual rotation is nonzero.
-/

namespace EFMW

open Real

/-! ## Emergence and fifth forces (ME-051 … ME-053) -/

/-- **ME-051** — the emergence force `F_em = −∇U(Φ) + λ∇R`, one-dimensional. -/
noncomputable def emergenceForce (U R : ℝ → ℝ) (lam : ℝ) (Phi : ℝ) : ℝ :=
  -deriv U Phi + lam * deriv R Phi

/-- **The emergence force is restoring.**  Inside the coherent well
(`0 < Φ`, `Φ² < b/a`) the force generated by the ME-025 potential pushes the
order parameter up towards the minimum at `Φ² = b/a`. -/
theorem emergenceForce_restoring_inner {a b Phi : ℝ} (ha : 0 < a) (hPhi : 0 < Phi)
    (h : Phi ^ 2 < b / a) :
    0 < emergenceForce (coherencePotential a b) (fun _ => 0) 0 Phi := by
  have hderiv : deriv (coherencePotential a b) Phi = a * Phi ^ 3 - b * Phi :=
    (hasDerivAt_coherencePotential a b Phi).deriv
  have hab : a * Phi ^ 2 < b := by
    rw [lt_div_iff₀ ha] at h
    nlinarith
  simp only [emergenceForce, hderiv, zero_mul, add_zero]
  nlinarith

/-- Outside the well the force points back inwards. -/
theorem emergenceForce_restoring_outer {a b Phi : ℝ} (ha : 0 < a) (hPhi : 0 < Phi)
    (h : b / a < Phi ^ 2) :
    emergenceForce (coherencePotential a b) (fun _ => 0) 0 Phi < 0 := by
  have hderiv : deriv (coherencePotential a b) Phi = a * Phi ^ 3 - b * Phi :=
    (hasDerivAt_coherencePotential a b Phi).deriv
  have hab : b < a * Phi ^ 2 := by
    rw [div_lt_iff₀ ha] at h
    nlinarith
  simp only [emergenceForce, hderiv, zero_mul, add_zero]
  nlinarith

/-- **ME-053** — the scalar fifth force `F_φ = −(β_φ/M)∇φ`. -/
noncomputable def fifthForce (beta mass : ℝ) (phiField : ℝ → ℝ) (x : ℝ) : ℝ :=
  -(beta / mass) * deriv phiField x

/-- A uniform coherence field exerts no fifth force. -/
theorem fifthForce_const (beta mass c x : ℝ) : fifthForce beta mass (fun _ => c) x = 0 := by
  simp [fifthForce]

/-- **ME-054** — the modified geodesic equation
`ẍ^μ + Γ^μ_αβ ẋ^α ẋ^β = β_φ(g^μν + u^μu^ν)∇_νφ`. -/
def modifiedGeodesic (acc : Fin 4 → ℝ) (Gamma : Fin 4 → Fin 4 → Fin 4 → ℝ)
    (u : Fin 4 → ℝ) (gInv : Fin 4 → Fin 4 → ℝ) (dphi : Fin 4 → ℝ) (beta : ℝ) : Prop :=
  ∀ mu, acc mu + ∑ al : Fin 4, ∑ be : Fin 4, Gamma mu al be * u al * u be
      = beta * ∑ nu : Fin 4, (gInv mu nu + u mu * u nu) * dphi nu

/-- With vanishing scalar coupling the modified geodesic equation is exactly the
standard geodesic equation: the extension is conservative in `β_φ`. -/
theorem modifiedGeodesic_beta_zero (acc : Fin 4 → ℝ) (Gamma : Fin 4 → Fin 4 → Fin 4 → ℝ)
    (u : Fin 4 → ℝ) (gInv : Fin 4 → Fin 4 → ℝ) (dphi : Fin 4 → ℝ) :
    modifiedGeodesic acc Gamma u gInv dphi 0 ↔
      ∀ mu, acc mu + ∑ al : Fin 4, ∑ be : Fin 4, Gamma mu al be * u al * u be = 0 := by
  simp [modifiedGeodesic]

/-! ## Rotating-universe cosmology (ME-056 … ME-058) -/

/-- The standard Friedmann right-hand side. -/
noncomputable def friedmannLCDM (Gnewton rho Lam k a : ℝ) : ℝ :=
  (8 * π * Gnewton / 3) * rho + Lam / 3 - k / a ^ 2

/-- **ME-056** — the rotating-universe Friedmann extension
`H² = (8πG/3)ρ + Λ/3 − k/a² + Ω_U²/a²`. -/
noncomputable def friedmannEFMW (Gnewton rho Lam k a OmegaU : ℝ) : ℝ :=
  friedmannLCDM Gnewton rho Lam k a + OmegaU ^ 2 / a ^ 2

/-- **ME-058** — the cosmic deviation parameter is exactly the rotational
contribution. -/
theorem friedmann_deviation (Gnewton rho Lam k a OmegaU : ℝ) :
    friedmannEFMW Gnewton rho Lam k a OmegaU - friedmannLCDM Gnewton rho Lam k a
      = OmegaU ^ 2 / a ^ 2 := by
  simp [friedmannEFMW]

/-- Residual rotation can only increase the expansion rate. -/
theorem friedmannEFMW_ge (Gnewton rho Lam k a OmegaU : ℝ) :
    friedmannLCDM Gnewton rho Lam k a ≤ friedmannEFMW Gnewton rho Lam k a OmegaU := by
  have : 0 ≤ OmegaU ^ 2 / a ^ 2 := by positivity
  simp only [friedmannEFMW]
  linarith

/-- The increase is strict exactly when the residual rotation is nonzero. -/
theorem friedmannEFMW_lt_iff {Gnewton rho Lam k a OmegaU : ℝ} (ha : a ≠ 0) :
    friedmannLCDM Gnewton rho Lam k a < friedmannEFMW Gnewton rho Lam k a OmegaU ↔
      OmegaU ≠ 0 := by
  have ha2 : (0:ℝ) < a ^ 2 := by positivity
  simp only [friedmannEFMW, lt_add_iff_pos_right]
  constructor
  · intro h hO
    rw [hO] at h
    simp at h
  · intro hO
    have : 0 < OmegaU ^ 2 := by positivity
    exact div_pos this ha2

/-- **ME-057** — the expanded effective cosmic density
`ρ_eff = ρ_ΛCDM + ρ_rot + ρ_lin + ρ_HE`. -/
def effectiveDensity (rhoLCDM rhoRot rhoLin rhoHE : ℝ) : ℝ :=
  rhoLCDM + rhoRot + rhoLin + rhoHE

theorem effectiveDensity_ge {rhoLCDM rhoRot rhoLin rhoHE : ℝ}
    (h1 : 0 ≤ rhoRot) (h2 : 0 ≤ rhoLin) (h3 : 0 ≤ rhoHE) :
    rhoLCDM ≤ effectiveDensity rhoLCDM rhoRot rhoLin rhoHE := by
  simp only [effectiveDensity]
  linarith

end EFMW
